import swaggerJsdoc from "swagger-jsdoc";

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Product CRUD API",
      version: "1.0.0",
      description:
        "API documentation for Authentication and Product CRUD application built with Express.js and MongoDB.",
    },

    servers: [
      {
        url: "http://localhost:5000",
        description: "Local Development Server",
      },
    ],

    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },

      schemas: {
        Register: {
          type: "object",
          required: ["name", "email"],
          properties: {
            name: {
              type: "string",
              example: "Bhumi",
            },
            email: {
              type: "string",
              example: "bhumi@gmail.com",
            },
          },
          description:
            "A temporary password is generated by the server and emailed to the user — it is not provided by the client.",
        },

        Login: {
          type: "object",
          required: ["email", "password"],
          properties: {
            email: {
              type: "string",
              example: "bhumi@gmail.com",
            },
            password: {
              type: "string",
              example: "Bhumi@123",
            },
          },
        },

        Product: {
          type: "object",
          required: ["name", "price", "category"],
          properties: {
            name: {
              type: "string",
              example: "Laptop",
            },
            category: {
              type: "string",
              example: "Electronics",
            },
            price: {
              type: "number",
              example: 50000,
            },
            image: {
              type: "string",
              format: "binary",
              description: "Product image file (jpg, jpeg, png, webp — max 5MB).",
            },
          },
        },
      },
    },
  },

  apis: ["./docs/*.js", "./routes/*.js"],
};

const swaggerSpec = swaggerJsdoc(options);

export default swaggerSpec;